In [157]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

### Solving Non-Singular System of Linear Equations

#### Material

Process Manipulating Equations:
- Swapping equations
- Adding / subtracting equations
- Multiplying / dividing equations by a constant

**System:**

- $5a + b = 17$
- $4a - 3b = 6$

Divide by coefficient of a

\begin{align*}
    a + 0.2b &= 3.4     \\
    a - 0.75b &= 1.5    \\
                        \\
    0.95b &= 1.9        \\
    b &= 2              \\
    a &= 3
\end{align*}

Solved System:
- $a = 3$
- $b = 2$

#### Quiz

System:

- $2a + 5b = 46$
- $8a + b = 32$

Step 1: Multiply Eq I with constant 4

\begin{align*}
  (2a + 5b = 46) * 4 \\
  8a + 10b = 184
\end{align*}

Step 2: Subtract Eq from Step 1 and Eq II

\begin{align*}
    8a + 20b &= 184     \\
    8a + b &= 32        \\
                        \\
    19b &= 152          \\
    b   &= 8            \\
    a   &= 3a
\end{align*}

Solved System:
- $a = 3$
- $b = 8a$

### Solving Singular System of Linear Equations

#### Material

**System: (Redundant)**

- $a + b = 10$
- $2a + 2b = 20$

Step 1: Divide Eq II with constant 2

\begin{align*}
  (2a + 2b = 20) / 2 \\
  a + b = 10
\end{align*}

Step 2: Subtract Eq from Step 1 and Eq II

\begin{align*}
    a + b &= 10     \\
    a + b &= 10     \\
                    \\
    0 &= 0          
\end{align*}

Solved System:
1. Degree of freedom
    - $a = x$
    - $b = 10 - x$
2. $a + b = 10$

**System: (Contradictory)**

- $a + b = 10$
- $2a + 2b = 24$

Step 1: Divide Eq II with constant 2

\begin{align*}
  (2a + 2b = 24) / 2 \\
  a + b = 12
\end{align*}

Step 2: Subtract Eq from Step 1 and Eq II

\begin{align*}
    a + b &= 10     \\
    a + b &= 12     \\
                    \\
    0 &= 2          
\end{align*}

No solved system

#### Quiz

**System: (Redundant)**

- $5a + b = 11$
- $10a + 2b = 22$

Step 1: Multiply Eq I with constant 2

\begin{align*}
  (5a + b = 11) * 2 \\
  10a + 2b = 22
\end{align*}

Step 2: Subtract Eq from Step 1 and Eq II

\begin{align*}
    10a + 2b &= 22     \\
    10a + 2b &= 22     \\
                        \\
    0 &= 0          
\end{align*}


Solved System (Infinite Solutions):
1. Degree of freedom
    - $a = x$
    - $b = 11 - 5x$
2. $5a + b = 11$

### Solving System of Equations with More Variables

#### Material

System:

- $a + b + 2c = 12$
- $3a - 3b - c = 3$
- $2a - b + 6c = 24$

**Elimination Method**

Step 1: Isolated $a$ (solved Eq II & III)

a. Divide Eq II with constant 3
\begin{align*}
  (3a - 3b - c = 3) / 3 \\
  a - b - \frac{1}{3}c = 1
\end{align*}

b. Divide Eq III with constant 2
\begin{align*}
  (2a - b + 6c = 24) / 2 \\
  a - \frac{1}{2}b + 3c = 12
\end{align*}

c. Subtract Eq I & Eq from Step 1a

\begin{align*}
  a + b + 2c &= 12 \\
  a - b - \frac{1}{3}c &= 1 \\
  \\
  2b + \frac{7}{3}c &= 11
\end{align*}


d. Subtract Eq I & Eq from Step 1b

\begin{align*}
  a + b + 2c &= 12 \\
  a - \frac{1}{2}b + 3c &= 12 \\
  \\
  \frac{3}{2}b - c &= 0
\end{align*}

Step 2: Isolated $b$ (Eq from Step 1c & 1d)

a. Divide Eq 1c with constant 2
\begin{align*}
  (2b + \frac{7}{3}c = 11) / 2 \\
  b + \frac{7}{6}c = \frac{11}{2}
\end{align*}

b. Multiply Eq 1d with constant 2/3
\begin{align*}
  (\frac{3}{2}b - c = 0) * \frac{2}{3} \\
  b - \frac{2}{3}c = 0
\end{align*}

c. Subtract Eq from Step 2a & 2b

\begin{align*}
  b + \frac{7}{6}c &= \frac{11}{2} \\
  b - \frac{2}{3}c &= 0 \\
  \\
  \frac{11}{6} c &= \frac{11}{2} \\
  \\
  c &= 3
\end{align*}

d. Replace c in Eq from Step 2a
\begin{align*}
  b + \frac{7}{6} * 3 &= \frac{11}{2} \\
  b + \frac{7}{2} &= \frac{11}{2} \\
  \\
  b &= 2
\end{align*}

e. Replace c & b  in Eq I
\begin{align*}
a + 2 + 2 * 3 &= 12 \\
a + 2 + 6 &= 12 \\
\\
a &= 4
\end{align*}

In [168]:
np.linalg.solve([[1,1,2],
                [3,-3,-1],
                [2,-1,6]], [12,3,24])

array([4., 2., 3.])

### Rank of a Matrix

#### Material

System:

- $a + b = 0$
- $a + 2b = 0$

In [170]:
matrix_1 = sp.Matrix([[1, 1],
                      [1, 2]])

In [171]:
matrix_1.rank()

2

- Two Equations, Two pieces of information
- Dimension of solution space = 0
- Rank = 2

System: 

- $a + b = 0$
- $2a + 2b = 0$

In [172]:
matrix_2 = sp.Matrix([[1, 1],
                      [2, 2]])

In [173]:
matrix_2.rank()

1

- Two Equations, One piece of information
- Dimension of solution space = 1
- Rank = 1

System:

- $0a + 0b = 0$
- $0a + 0b = 0$

- Two Equations, Zero pieces of information
- Dimension of solution space = 2
- Rank = 2

#### Quiz

Problem:

- Determine the rank of the following two matrices

In [8]:
np.array([[5,1],
          [-1,3]])

array([[ 5,  1],
       [-1,  3]])

- Dimension of solution = 0
- Rank = 2

In [9]:
np.array([[2,-1],
          [-6,3]])

array([[ 2, -1],
       [-6,  3]])

- Dimension of solution = 1
- Rank = 1

### Rank of Matrix: General Case

#### Material

System:

- $a + b + c = 0$
- $a + 2b + c = 0$
- $a + b + 2c = 0$

- 3 Equations
- 3 Pieces of Informations
- Rank = 3

System:

- $a + b + c = 0$
- $a + b + 2c = 0$ [X]
- $a + b + 3c = 0$

- 3 Equations
- 2 Pieces of Informations
- Rank = 2

System:

- $a + b + c = 0$
- $2a + 2b + 2c = 0$ [X]
- $3a + 3b + 3c = 0$ [X] 

- 3 Equations
- 1 Pieces of Informations
- Rank = 1

### Reduced Row Echelon Form

In [144]:
import sympy as sp

Full rank

In [158]:
matrix_1 = sp.Matrix([[5,1],
                      [4,-3]])

In [159]:
matrix_1.rref()

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

In [160]:
matrix_1.rank()

2

In [161]:
matrix_2 = sp.Matrix([[5,1],
                      [10,2]])

In [162]:
matrix_2.rref()

(Matrix([
 [1, 1/5],
 [0,   0]]),
 (0,))

In [163]:
matrix_2.rank()

1

In [164]:
matrix_3 = sp.Matrix([[0,0],
                      [0,0]])

In [165]:
matrix_3.rref()

(Matrix([
 [0, 0],
 [0, 0]]),
 ())

In [166]:
matrix_3.rank()

0

### Keypoints

- When the solution set is finite (Non-Singular), it is reduced to a single element
    - e.g: $(x=3,\;y=-2,\;z=6)$ or $(3, -2, 6)$
- To describe a set with an infinite number of solutions (Singular), typically some of the variables are designated as free (or independent, or as parameters).
    - e.g: $x = -7z -1$ and $y = 3z + 2$
    - $z$ is the free variable, while $x$ and $y$ are dependent on $z$
- Each free variable gives the solution space one degree of freedom, the number of which is equal to the dimension of the solution set
- There are several algorithms for solving a system of linear equations.
    1. Elimination of variables
    2. Row reduction
    3. Cramer's rule
    4. Matrix Solution
        - If the matrix A is square (has m rows and n=m columns) and has full rank (all m rows are independent), then the system has a unique solution